### ISSUE TITLE
are you going to build something like reddit?

### ISSUE THREAD

**Issue by mojocn** [nicolasparada/nakama#1]

**Comment by nicolasparada** [comment]
More like twitter.
I wanted to build a social network for anime fans, but at this point I don't know what "anime" features add to it... Not that I want to make a video site. That's too complex and even Netflix has started to stream anime. An anime list tracking site, well... there is already a bunch of sites like that with a big database of animes.
Maybe I'm just coding it to teach myself. I hope to attrack users by building a minimalist site.
