### ISSUE TITLE
PQ could not query 

### ISSUE THREAD

**Issue by yangwawa0323** [nicolasparada/nakama#46]
ts=2021-06-30T13:22:01.4652664Z mailing_implementation=log                                                            
ts=2021-06-30T13:22:01.4653348Z storage_implementation="os file system"                                               
ts=2021-06-30T13:22:01.4692399Z message="accepting connections" port=3000                                             
ts=2021-06-30T13:22:01.4692957Z message="starting server" origin=http://localhost:3000                                
ts=2021-06-30T13:26:28.4428699Z component=http error="could not query select user: pq: relation \"users\" does not exi
st"                                                                                                                   
ts=2021-06-30T13:26:36.6839883Z component=http error="could not query select user: pq: relation \"users\" does not exi
st"                                                                                                                   
ts=2021-06-30T13:28:58.4819565Z component=http error="could not query select timeline: pq: column \"posts.reactions\" 
does not exist"                                                                                                       
ts=2021-06-30T13:29:19.0210764Z component=http error="could not query select timeline: pq: column \"posts.reactions\" 
does not exist"                                                                                                       
ts=2021-06-30T13:29:25.8587493Z component=http error="could not query select posts: pq: column \"posts.reactions\" doe
s not exist"

**Comment by yangwawa0323** [comment]
In timeline_item.go file , I commentted the **buildQuery** function SELECT sql  posts.reactions, and also commentted corrsponed **rows.Scan** _&varReactions_, after rebuild it is working.

**Comment by nicolasparada** [comment]
I think you forgot to create the database and tables.
```
cockroach sql --insecure -e "CREATE DATABASE IF NOT EXISTS nakama;"
```
```
cat schema.sql | cockroach sql --insecure
```

**Comment by nicolasparada** [comment]
Closing this. Please ask anything, I'll try answering ;)
